#!/bin/bash
set -e

echo "What changes have you made?"
read commit_message
read -p "Have you verified your changes locally (y/n): " verified
if [ $verified = y ]
then
  git add .
  git commit -m "$commit_message"
  git push
  npm run deploy
else
  echo "Please verify your changes, run:"
  echo "  npm start"
fi